{{- if (and .Values.integrationTests.enabled .Values.monitoring.enabled) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "consul-integration-tests.name" . }}-monitoring-secret
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
stringData:
  prometheus-user: "{{ .Values.integrationTests.secret.prometheus.user }}"
  prometheus-password: "{{ .Values.integrationTests.secret.prometheus.password }}"
{{- end }}
