{{- if .Values.integrationTests.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "consul.fullname" . }}-integration-tests
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - list
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - delete
      - patch
  - apiGroups:
      - apps
    resources:
      - statefulsets/scale
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
    verbs:
      - list
      - get
  {{- if .Values.integrationTests.statusWritingEnabled }}
  - apiGroups:
      - apps
    resources:
      - deployments/status
    verbs:
      - get
      - list
      - update
      - patch
  {{- end }}
{{- end }}