{{- if (and .Values.integrationTests.enabled .Values.integrationTests.secret.aclToken) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "consul-integration-tests.name" . }}-secret
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
stringData:
  acl-token: "{{ .Values.integrationTests.secret.aclToken }}"
{{- end }}
