{{- if .Values.integrationTests.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "consul.fullname" . }}-integration-tests
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
{{- end }}
