{{- if eq (include "consul-status-provisioner.cleanupEnabled" .) "true" }}
# status-provisioner-cleanup deletes previous status-provisioner job if it exists
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "consul.fullname" . }}-status-provisioner-cleanup
  labels:
    name: {{ template "consul.fullname" . }}-status-provisioner-cleanup
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ template "consul.fullname" . }}-status-provisioner-cleanup
    app.kubernetes.io/instance: {{ cat (printf "%s-status-provisioner-cleanup"  (include "consul.fullname" .)) .Values.DELIMITER .Release.Namespace | nospace | trunc 63 }}
    app.kubernetes.io/technology: python
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    metadata:
      name: {{ template "consul.fullname" . }}-status-provisioner-cleanup
      labels:
        app: {{ template "consul.name" . }}
        chart: {{ template "consul.chart" . }}
        release: {{ .Release.Name }}
        component: status-provisioner-cleanup
        name: {{ template "consul.fullname" . }}-status-provisioner-cleanup
        app.kubernetes.io/name: {{ template "consul.fullname" . }}-status-provisioner-cleanup
    spec:
      {{- if not (eq (include "openshift.enabled" .) "true") }}
      securityContext:
        {{- include "consul.globalPodSecurityContext" . | nindent 8 }}
        {{- with .Values.statusProvisioner.securityContext }}
        {{- toYaml . | nindent 8 -}}
        {{- end }}
      {{- end }}
      restartPolicy: Never
      serviceAccountName: {{ template "consul.fullname" . }}-status-provisioner-cleanup
      containers:
        - name: status-provisioner-cleanup
          image: {{ template "deployment-status-provisioner.image" . }}
          command:
            - "/bin/bash"
            - "-c"
            - kubectl delete job {{ template "consul.fullname" . }}-status-provisioner --ignore-not-found=true
          resources:
            requests:
              cpu: {{ default "50m" .Values.statusProvisioner.resources.requests.cpu }}
              memory: {{ default "50Mi" .Values.statusProvisioner.resources.requests.memory }}
            limits:
              cpu: {{ default "100m" .Values.statusProvisioner.resources.limits.cpu }}
              memory: {{ default "100Mi" .Values.statusProvisioner.resources.limits.memory }}
          securityContext:
            {{- include "consul.globalContainerSecurityContext" . | nindent 12 }}
{{- end }}