{{- if eq (include "consul-status-provisioner.cleanupEnabled" .) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "consul.fullname" . }}-status-provisioner-cleanup
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - delete
{{- end }}