# permissions for end users to edit consulacls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consulacl-editor-role
rules:
- apiGroups:
  - netcracker.com
  resources:
  - consulacls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netcracker.com
  resources:
  - consulacls/status
  verbs:
  - get
