apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: consul-client
  annotations:
    kubernetes.io/description: consul-client are the security context constraints required
      to run the consul client.
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: []
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
groups: []
priority: 0
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - KILL
  - MKNOD
  - SETUID
  - SETGID
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: MustRunAs
users: []
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consul-client
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames:
      - consul-client
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-client
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: consul-client
subjects:
  - kind: ServiceAccount
    name: consul-client
    namespace: consul-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consul-auth-method
rules:
  - apiGroups: [""]
    resources:
      - serviceaccounts
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-authdelegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "system:auth-delegator"
subjects:
  - kind: ServiceAccount
    name: consul-connect-injector-authmethod-svc-account
    namespace: consul-service
  - kind: ServiceAccount
    name: consul-auth-method
    namespace: consul-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-auth-method
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: consul-auth-method
subjects:
  - kind: ServiceAccount
    name: consul-connect-injector-authmethod-svc-account
    namespace: consul-service
  - kind: ServiceAccount
    name: consul-auth-method
    namespace: consul-service
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: consul-acl-configurator-operator
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs:
      - get
      - create
      - list
      - update
      - watch
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - services
      - persistentvolumeclaims
      - secrets
    verbs:
      - get
      - create
      - list
      - update
      - watch
      - patch
      - delete
  - apiGroups:
      - qubership.org
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: consul-acl-configurator-operator
subjects:
  - kind: ServiceAccount
    name: consul-acl-configurator-operator
    namespace: consul-service
roleRef:
  kind: ClusterRole
  name: consul-acl-configurator-operator
  apiGroup: rbac.authorization.k8s.io
