---
# Source: consul/templates/auth-method-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consul-auth-method-consul-service
rules:
  - apiGroups: [""]
    resources:
      - serviceaccounts
    verbs:
      - get
---
# Source: consul/templates/auth-method-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-authdelegator-consul-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "system:auth-delegator"
subjects:
  - kind: ServiceAccount
    name: consul-auth-method
    namespace: consul-service
---
# Source: consul/templates/auth-method-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-auth-method-consul-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: consul-auth-method-consul-service
subjects:
  - kind: ServiceAccount
    name: consul-auth-method
    namespace: consul-service
---
# Source: consul/templates/consul_acl_configurator/acl-configurator-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: consul-acl-configurator-operator-consul-service
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs:
      - get
      - create
      - list
      - update
      - watch
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - services
      - persistentvolumeclaims
      - secrets
    verbs:
      - get
      - create
      - list
      - update
      - watch
      - patch
      - delete
  - apiGroups:
      - netcracker.com
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
# Source: consul/templates/consul_acl_configurator/acl_configurator_clusterrole_binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: consul-acl-configurator-operator-consul-service
subjects:
  - kind: ServiceAccount
    name: consul-acl-configurator-operator
    namespace: consul-service
roleRef:
  kind: ClusterRole
  name: consul-acl-configurator-operator-consul-service
  apiGroup: rbac.authorization.k8s.io