DEPLOY_W_HELM: "true"
global:
  enabled: true
  enablePodSecurityPolicies: true
  tls:
    enabled: false
    httpsOnly: false
    certManager:
      enabled: true
      durationDays: 730
      clusterIssuerName: qa-issuer-self
  acls:
    manageSystemACLs: true
  federation:
    enabled: false
server:
  enabled: true
  nodeSelector:
    role: compute
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: consul
              release: consul-service
              component: server
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - worker1
                  - worker2
                  - worker3
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 99
          preference:
            matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - worker1
        - weight: 50
          preference:
            matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - worker2
        - weight: 1
          preference:
            matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - worker3
  replicas: 3
  bootstrapExpect: 3
  storage: 1Gi
  storageClass: csi-cinder-sc-delete
  connect: true
  updatePartition: 0
  disruptionBudget:
    enabled: true
  tolerations: {}
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 1024Mi
      cpu: 100m
consulAclConfigurator:
  enabled: true
  name: consul-acl-configurator
  reconcilePeriod: 100
  namespaces: ""
  serviceName: consul-acl-configurator-reconcile
  consul:
    port: 8500
dns:
  enabled: "-"
monitoring:
  enabled: true
  consulExecPluginInterval: 30s
  consulExecPluginTimeout: 20s
  monitoringType: prometheus
  installDashboard: true
  consulScriptDebug: ""
ui:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: consul-consul-service.qa-kubernetes.openshift.sdntest.netcracker.com
  service:
    enabled: true
client:
  enabled: true
  nodeSelector:
    role: compute
  resources:
    requests:
      memory: 64Mi
      cpu: 25m
    limits:
      memory: 256Mi
      cpu: 50m
ingressGateways:
  enabled: false
backupDaemon:
  enabled: true
  storage: 1Gi
  storageClass: csi-cinder-sc-delete
  backupSchedule: 0 0 * * *
  evictionPolicy: 0/1d,7d/delete
statusProvisioner:
  enabled: true
  podReadinessTimeout: 300
  integrationTestsTimeout: 3000
integrationTests:
  enabled: true
  tags: backupORcrud
  prometheusUrl: http://prometheus.qa-kubernetes.openshift.sdntest.netcracker.com
ESCAPE_SEQUENCE: "true"
