DEPLOY_W_HELM: "true"
ENABLE_PRIVILEGED_PSS: "true"
global:
  enabled: true
  tls:
    enabled: true
    httpsOnly: false
    certManager:
      enabled: true
      durationDays: 730
      clusterIssuerName: qa-clusterissuer
  disasterRecovery:
    enabled: true
    mode: active
    region: one
    httpAuth:
      enabled: true
      smNamespace: site-manager
      smServiceAccountName: sm-auth-sa
server:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: consul
              release: consul-service
              component: server
          topologyKey: kubernetes.io/hostname
  replicas: 3
  bootstrapExpect: 3
  storage: 1Gi
  storageClass: custom-csi-cinder-delete
  resources:
    limits:
      memory: 300Mi
      cpu: 100m
consulAclConfigurator:
  enabled: true
dns:
  enabled: false
monitoring:
  enabled: true
ui:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: consul-consul-service.platcert01.kubernetes.sdntest.netcracker.com
  service:
    enabled: true
client:
  enabled: true
  nodeSelector:
    node-role.kubernetes.io/worker: worker
  resources:
    requests:
      memory: 64Mi
      cpu: 25m
    limits:
      memory: 256Mi
      cpu: 25m
backupDaemon:
  enabled: true
  backupSchedule: "*/15 * * * *"
  evictionPolicy: 1h/1d,7d/delete
  s3:
    enabled: true
    url: http://test-minio-gateway-nas.qa-kubernetes.openshift.sdntest.netcracker.com/
    bucket: consul-qa
    keyId: Z4nz2bxWnWM36lf3K21y
    keySecret: oqtAdywaB7c7OJWHQ9rLVuJcKjpUR8iSJfXMPCLr
integrationTests:
  enabled: true
  tags: backupORcrudORhaORalertsORbackupORconsul_images
  prometheusUrl: http://vmsingle-k8s.prometheus-operator:8429
statusProvisioner:
  integrationTestsTimeout: 1500
  podReadinessTimeout: 900
ESCAPE_SEQUENCE: "true"
