apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "consul.fullname" . }}-update-resources
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation