{{- if .Values.consulAclConfigurator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "consul-acl-configurator.name" . }}-jwks-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
spec:
  selector:
    name: {{ template "consul-acl-configurator.name" . }}-jwks-proxy
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
{{- end }}
