{{- if and .Values.consulAclConfigurator.enabled (ne (include "consul.restrictedEnvironment" .) "true") }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "consul-acl-configurator.name" . }}-operator-{{ .Release.Namespace }}
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs:
      - get
      - create
      - list
      - update
      - watch
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - services
      - persistentvolumeclaims
      - secrets
    verbs:
      - get
      - create
      - list
      - update
      - watch
      - patch
      - delete
  - apiGroups:
      - {{ .Values.consulAclConfigurator.apiGroup }}
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
{{- end }}
