{{- if and .Values.consulAclConfigurator.enabled (ne (include "consul.restrictedEnvironment" .) "true") }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "consul-acl-configurator.name" . }}-operator-{{ .Release.Namespace }}
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "consul-acl-configurator.name" . }}-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "consul-acl-configurator.name" . }}-operator-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}