{{- if .Values.consulAclConfigurator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "consul-acl-configurator.name" . }}-operator
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
{{- end }}
