{{- if (ne (include "consul.restrictedEnvironment" .) "true") }}
{{- if .Values.global.acls.manageSystemACLs }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "consul.fullname" . }}-auth-method-{{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: auth-method
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - serviceaccounts
    verbs:
      - get
{{- end }}
{{- end }}