# This resource is required for correct work of ACL init job, because Kubernetes does not generate tokens for service accounts automatically since 1.22 version.
{{- if .Values.global.acls.manageSystemACLs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "consul.fullname" . }}-auth-method
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: auth-method
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ template "consul.fullname" . }}-auth-method
type: kubernetes.io/service-account-token
{{- end }}