{{- if (or (and (ne (.Values.backupDaemon.enabled | toString) "-") .Values.backupDaemon.enabled) (and (eq (.Values.backupDaemon.enabled | toString) "-") .Values.global.enabled)) }}
{{- if not .Values.client.snapshotAgent.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "consul.fullname" . }}-snapshot-agent
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "consul.fullname" . }}-snapshot-agent
roleRef:
  kind: Role
  name: {{ template "consul.fullname" . }}-snapshot-agent
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}