{{- if .Values.backupDaemon.s3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "consul.fullname" . }}-s3-secret
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
type: Opaque
stringData:
  s3-key-id: {{ .Values.backupDaemon.s3.keyId }}
  s3-key-secret: {{ .Values.backupDaemon.s3.keySecret }}
{{- end }}