{{- if (or (and (ne (.Values.backupDaemon.enabled | toString) "-") .Values.backupDaemon.enabled) (and (eq (.Values.backupDaemon.enabled | toString) "-") .Values.global.enabled)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "consul.fullname" . }}-backup-daemon-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    release: {{ .Release.Name }}
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
type: Opaque
stringData:
  username: "{{ .Values.backupDaemon.username }}"
  password: "{{ .Values.backupDaemon.password }}"
{{- end }}