{{- if and .Values.global.tls.enabled .Values.backupDaemon.tls.enabled .Values.global.tls.certManager.enabled .Values.backupDaemon.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "consul.fullname" . }}-backup-daemon-tls-certificate
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
spec:
  secretName: {{ template "backupDaemon.tlsSecretName" . }}
  duration: {{ default 365 .Values.global.tls.certManager.durationDays | mul 24 }}h0m0s
  commonName: consul-backup-daemon-ca
  isCA: false
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
{{ include "backupDaemon.certDnsNames" . | indent 4 }}
  ipAddresses:
{{ include "backupDaemon.certIpAddresses" . | indent 4 }}
  issuerRef:
  {{- if .Values.global.tls.certManager.clusterIssuerName }}
    name: {{ .Values.global.tls.certManager.clusterIssuerName }}
    kind: ClusterIssuer
  {{- else }}
    name: {{ template "consul.fullname" . }}-tls-server-issuer
    kind: Issuer
  {{- end }}
    group: cert-manager.io
{{- end }}
