{{- if (or (and (ne (.Values.backupDaemon.enabled | toString) "-") .Values.backupDaemon.enabled) (and (eq (.Values.backupDaemon.enabled | toString) "-") .Values.global.enabled)) }}
{{- if not .Values.client.snapshotAgent.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "consul.fullname" . }}-snapshot-agent
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
{{- if .Values.global.acls.manageSystemACLs }}
rules:
  - apiGroups: [""]
    resources:
      - secrets
      - serviceaccounts
    verbs:
      - get
      - patch
  - apiGroups: [""]
    resources:
      - pods
      - pods/exec
    verbs:
      - get
      - list
      - delete
{{- else }}
rules: []
{{- end }}
{{- end }}
{{- end }}
