{{- if eq (.Values.client.enabled | toString) "true" }}
# ConfigMap with extra configuration specified directly to the chart
# for client agents only.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "consul.fullname" . }}-client-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: client
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
data:
  log-level.json: |-
    {
      {{- if .Values.client.logLevel }}
      "log_level": "{{ .Values.client.logLevel | upper }}"
      {{- end }}
    }
  central-config.json: |-
    {
      "enable_central_service_config": true
    }

  {{- if .Values.connectInject.enabled }}
  {{/* We set check_update_interval to 0s so that check output is immediately viewable
       in the UI. */}}
  config.json: |-
    {
      "check_update_interval": "0s"
    }
  {{- end }}
{{- end }}
