{{- if eq (.Values.client.enabled | toString) "true" }}
{{- if (or .Values.global.enablePodSecurityPolicies (eq (include "openshift.enabled" .) "true")) }}
{{- if (ne (include "consul.restrictedEnvironment" .) "true") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "consul.fullname" . }}-client-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
rules:
{{- if .Values.global.enablePodSecurityPolicies }}
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    resourceNames:
    {{- if (ne (include "consul.restrictedEnvironment" .) "true") }}
    - {{ template "consul.fullname" . }}-client
    {{- else }}
    - {{ .Values.client.podSecurityPolicy }}
    {{- end }}
    verbs:
    - use
{{- end }}
{{- if (eq (include "openshift.enabled" .) "true") }}
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames:
      {{- if (ne (include "consul.restrictedEnvironment" .) "true") }}
      - {{ template "consul.fullname" . }}-client
      {{- else }}
      - {{ .Values.client.securityContextConstraint }}
        {{- end }}
    verbs:
      - use
{{- end }}
{{- end }}
{{- end }}
{{- end }}