{{- if and (ne (include "consul.restrictedEnvironment" .) "true") (or (and (ne (.Values.connectInject.enabled | toString) "-") .Values.connectInject.enabled) (and (eq (.Values.connectInject.enabled | toString) "-") .Values.global.enabled)) }}
# The ClusterRole to enable the Connect injector to get, list, watch and patch MutatingWebhookConfiguration.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "consul.fullname" . }}-connect-injector
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: connect-injector
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
rules:
- apiGroups:
    - consul.hashicorp.com
  resources:
    - servicedefaults
    - serviceresolvers
    - proxydefaults
    - meshes
    - exportedservices
    - servicerouters
    - servicesplitters
    - serviceintentions
    - ingressgateways
    - terminatinggateways
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - consul.hashicorp.com
  resources:
    - servicedefaults/status
    - serviceresolvers/status
    - proxydefaults/status
    - meshes/status
    - exportedservices/status
    - servicerouters/status
    - servicesplitters/status
    - serviceintentions/status
    - ingressgateways/status
    - terminatinggateways/status
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
{{- if .Values.global.acls.manageSystemACLs }}
- apiGroups: [ "" ]
  resources:
    - serviceaccounts
    - secrets
  verbs:
    - get
{{- end }}
- apiGroups: [""]
  resources: ["pods", "endpoints", "services", "namespaces", "nodes"]
  verbs:
    - "get"
    - "list"
    - "watch"
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - create
    - get
    - list
    - update
- apiGroups: [ "" ]
  resources:
    - pods
  verbs:
    - "get"
    - "list"
    - "watch"
    - "update"
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - create
    - get
    - list
    - update
{{- end }}
