{{- if .Values.global.federation.createFederationSecret }}
{{- if not .Values.global.federation.enabled }}{{ fail "global.federation.enabled must be true when global.federation.createFederationSecret is true" }}{{ end }}
{{- if and (not .Values.global.acls.createReplicationToken) .Values.global.acls.manageSystemACLs }}{{ fail "global.acls.createReplicationToken must be true when global.acls.manageSystemACLs is true because the federation secret must include the replication token" }}{{ end }}
{{- if eq (int .Values.server.updatePartition) 0 }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "consul.fullname" . }}-create-federation-secret
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: create-federation-secret
    {{- if .Values.global.extraLabels }}
      {{- toYaml .Values.global.extraLabels | nindent 4 }}
    {{- end }}
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
    name: {{ template "consul.fullname" . }}-create-federation-secret
    app.kubernetes.io/name: {{ template "consul.fullname" . }}-create-federation-secret
    app.kubernetes.io/instance: {{ cat (printf "%s-create-federation-secret"  (include "consul.fullname" .)) .Values.DELIMITER .Release.Namespace | nospace | trunc 63 }}
    app.kubernetes.io/technology: python
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    {{- /* Hook weight needs to be 1 so that the service account is provisioned first */}}
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 10
  template:
    metadata:
      name: {{ template "consul.fullname" . }}-create-federation-secret
      labels:
        app: {{ template "consul.name" . }}
        chart: {{ template "consul.chart" . }}
        release: {{ .Release.Name }}
        component: create-federation-secret
        {{- if .Values.global.extraLabels }}
          {{- toYaml .Values.global.extraLabels | nindent 8 }}
        {{- end }}
        app.kubernetes.io/name: {{ template "consul.fullname" . }}-create-federation-secret
        name: {{ template "consul.fullname" . }}-create-federation-secret
      annotations:
        "consul.hashicorp.com/connect-inject": "false"
    spec:
      {{- if not (eq (include "openshift.enabled" .) "true") }}
      securityContext:
        {{- include "consul.globalPodSecurityContext" . | nindent 8 }}
        {{- with .Values.global.federation.securityContext }}
        {{- toYaml . | nindent 8 -}}
        {{- end }}
      {{- end }}
      restartPolicy: Never
      serviceAccountName: {{ template "consul.fullname" . }}-create-federation-secret
      volumes:
        {{- /* We can assume tls is enabled because there is a check in server-statefulset
          that requires tls to be enabled if federation is enabled. */}}
        - name: consul-ca-cert
          secret:
            secretName: {{ template "consul.caCertSecretName" . }}
            items:
              - key: {{ default "tls.crt" .Values.global.tls.caCert.secretKey }}
                path: tls.crt
        - name: consul-ca-key
          secret:
            {{- if .Values.global.tls.caKey.secretName }}
            secretName: {{ .Values.global.tls.caKey.secretName }}
            {{- else }}
            secretName: {{ template "consul.caCertKeySecretName" . }}
            {{- end }}
            items:
              - key: {{ default "tls.key" .Values.global.tls.caKey.secretKey }}
                path: tls.key
        {{- if (and .Values.global.gossipEncryption.secretName .Values.global.gossipEncryption.secretKey) }}
        - name: gossip-encryption-key
          secret:
            secretName: {{ .Values.global.gossipEncryption.secretName }}
            items:
              - key: {{ .Values.global.gossipEncryption.secretKey }}
                path: gossip.key
        {{- end }}

      containers:
        - name: create-federation-secret
          image: "{{ template "consul-k8s.image" . }}"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONSUL_HTTP_ADDR
              value: "https://{{ template "consul.fullname" . }}-server.{{ .Release.Namespace }}.svc:8501"
            - name: CONSUL_CACERT
              value: /consul/tls/ca/tls.crt
          volumeMounts:
            - name: consul-ca-cert
              mountPath: /consul/tls/ca
              readOnly: true
            - name: consul-ca-key
              mountPath: /consul/tls/server/ca
              readOnly: true
            {{- if (and .Values.global.gossipEncryption.secretName .Values.global.gossipEncryption.secretKey) }}
            - name: gossip-encryption-key
              mountPath: /consul/gossip
              readOnly: true
            {{- end }}
          command:
            - "/bin/sh"
            - "-ec"
            - |
                consul-k8s-control-plane create-federation-secret \
                  {{- if (and .Values.global.gossipEncryption.secretName .Values.global.gossipEncryption.secretKey) }}
                  -gossip-key-file=/consul/gossip/gossip.key \
                  {{- end }}
                  {{- if .Values.global.acls.createReplicationToken }}
                  -export-replication-token=true \
                  {{- end }}
                  -mesh-gateway-service-name={{ .Values.meshGateway.consulServiceName }} \
                  -k8s-namespace="${NAMESPACE}" \
                  -resource-prefix="{{ template "consul.fullname" . }}" \
                  -server-ca-cert-file=/consul/tls/ca/tls.crt \
                  -server-ca-key-file=/consul/tls/server/ca/tls.key \
                  -consul-api-timeout={{ .Values.global.consulAPITimeout }}
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "50Mi"
              cpu: "50m"
          securityContext:
            {{- include "consul.globalContainerSecurityContext" . | nindent 12 }}
{{- end }}
{{- end }}