{{- if (or (and (ne (.Values.dns.enabled | toString) "-") .Values.dns.enabled) (and (eq (.Values.dns.enabled | toString) "-") .Values.global.enabled)) }}
# Service for Consul DNS.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "consul.fullname" . }}-dns
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: dns
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ template "consul.fullname" . }}-dns
    name: {{ template "consul.fullname" . }}-dns
  {{- if .Values.dns.annotations }}
  annotations:
    {{ .Values.dns.annotations | toYaml | indent 4 | trim }}
  {{- end }}
spec:
{{- if .Values.dns.type }}
  type: {{ .Values.dns.type }}
{{- end }}
{{- if .Values.dns.clusterIP }}
  clusterIP: {{ .Values.dns.clusterIP }}
{{- end }}
  ports:
    - name: dns-tcp
      port: 53
      protocol: "TCP"
      targetPort: dns-tcp
    - name: dns-udp
      port: 53
      protocol: "UDP"
      targetPort: dns-udp
  selector:
    app: {{ template "consul.name" . }}
    release: "{{ .Release.Name }}"
    hasDNS: "true"
  {{- if .Values.dns.additionalSpec }}
  {{ .Values.dns.additionalSpec | toYaml | indent 2 | trim }}
  {{- end }}
{{- end }}
