{{- if (and (ne (include "consul.restrictedEnvironment" .) "true") .Values.meshGateway.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "consul.fullname" . }}-mesh-gateway
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: mesh-gateway
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
{{- if or .Values.global.acls.manageSystemACLs .Values.global.enablePodSecurityPolicies (eq .Values.meshGateway.wanAddress.source "Service") }}
rules:
{{- if .Values.global.acls.manageSystemACLs }}
  - apiGroups: [""]
    resources:
      - secrets
    resourceNames:
      - {{ template "consul.fullname" . }}-mesh-gateway-acl-token
    verbs:
      - get
{{- end }}
{{- if eq .Values.meshGateway.wanAddress.source "Service" }}
  - apiGroups: [""]
    resources:
      - services
    resourceNames:
      - {{ template "consul.fullname" . }}-mesh-gateway
    verbs:
      - get
  {{- end }}
{{- else }}
rules: []
{{- end }}
{{- end }}
