{{- if and .Values.server.serverLocalityEnabled (ne (include "consul.restrictedEnvironment" .) "true") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "consul.fullname" . }}-server-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: server
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs:
  - get
{{- end }}