{{- if (or (and (ne (.Values.server.enabled | toString) "-") .Values.server.enabled) (and (eq (.Values.server.enabled | toString) "-") .Values.global.enabled)) }}
{{- if not (empty .Values.server.persistentVolumes) }}
{{- $release := .Release }}
{{- $storageClass := (include "server.storageClass" .) }}
{{- $consul_fullname := printf "%s" (include "consul.fullname" .) }}
{{- range $index, $pvName := .Values.server.persistentVolumes }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-{{ $release.Namespace }}-{{ $consul_fullname }}-server-{{ $index }}
  labels:
    {{- include "consul-service.defaultLabels" $ | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: {{ $pvName }}
  storageClassName: "{{ $storageClass }}"
---
{{- end }}
{{- end }}
{{- end }}