{{- if (or (and (ne (.Values.server.enabled | toString) "-") .Values.server.enabled) (and (eq (.Values.server.enabled | toString) "-") .Values.global.enabled)) }}
{{- if and .Values.global.tls.enabled (not .Values.global.tls.certManager.enabled) (not (eq (include "server.certificatesSpecified" .) "true")) }}
# tls-init job generate Consul cluster CA and certificates for the Consul servers
# and creates Kubernetes secrets for them.
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "consul.fullname" . }}-tls-init
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
    name: {{ template "consul.fullname" . }}-tls-init
    app.kubernetes.io/name: {{ template "consul.fullname" . }}-tls-init
    app.kubernetes.io/instance: {{ cat (printf "%s-tls-init"  (include "consul.fullname" .)) .Values.DELIMITER .Release.Namespace | nospace | trunc 63 }}
    app.kubernetes.io/technology: python
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: {{ template "consul.fullname" . }}-tls-init
      labels:
        app: {{ template "consul.name" . }}
        chart: {{ template "consul.chart" . }}
        release: {{ .Release.Name }}
        component: tls-init
        {{- with .Values.global.extraLabels }}
          {{- toYaml . | nindent 8 -}}
        {{- end }}
        name: {{ template "consul.fullname" . }}-tls-init
        app.kubernetes.io/name: {{ template "consul.fullname" . }}-tls-init
      annotations:
        "consul.hashicorp.com/connect-inject": "false"
    spec:
      {{- if not (eq (include "openshift.enabled" .) "true") }}
      securityContext:
        {{- include "server.securityContext" . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      serviceAccountName: {{ template "consul.fullname" . }}-tls-init
      {{- if (and .Values.global.tls.caCert.secretName .Values.global.tls.caKey.secretName) }}
      volumes:
      - name: consul-ca-cert
        secret:
          secretName: {{ .Values.global.tls.caCert.secretName }}
          items:
          - key: {{ default "tls.crt" .Values.global.tls.caCert.secretKey }}
            path: tls.crt
      - name: consul-ca-key
        secret:
          secretName: {{ .Values.global.tls.caKey.secretName }}
          items:
          - key: {{ default "tls.key" .Values.global.tls.caKey.secretKey }}
            path: tls.key
      {{- end }}
      containers:
        - name: tls-init
          image: "{{ template "consul-k8s.image" . }}"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          workingDir: /tmp
          command:
            - "/bin/sh"
            - "-ec"
            - |
              # Suppress globbing so we can interpolate the $NAMESPACE environment variable
              # and use * at the start of the dns name when setting -additional-dnsname.
              set -o noglob
              consul-k8s-control-plane tls-init \
                -domain={{ .Values.global.domain }} \
                -days=730 \
                -name-prefix={{ template "consul.fullname" . }} \
                -k8s-namespace=${NAMESPACE} \
                {{- if (and .Values.global.tls.caCert.secretName .Values.global.tls.caKey.secretName) }}
                -ca=/consul/tls/ca/cert/tls.crt \
                -key=/consul/tls/ca/key/tls.key \
                {{- end }}
                -additional-dnsname="{{ template "consul.fullname" . }}-server" \
                -additional-dnsname="*.{{ template "consul.fullname" . }}-server" \
                -additional-dnsname="*.{{ template "consul.fullname" . }}-server.${NAMESPACE}" \
                -additional-dnsname="{{ template "consul.fullname" . }}-server.${NAMESPACE}" \
                -additional-dnsname="*.{{ template "consul.fullname" . }}-server.${NAMESPACE}.svc" \
                -additional-dnsname="{{ template "consul.fullname" . }}-server.${NAMESPACE}.svc" \
                -additional-dnsname="*.server.{{ .Values.global.datacenter }}.{{ .Values.global.domain }}" \
                {{- range .Values.global.tls.serverAdditionalIPSANs }}
                -additional-ipaddress={{ . }} \
                {{- end }}
                {{- range .Values.global.tls.serverAdditionalDNSSANs }}
                -additional-dnsname={{ . }} \
                {{- end }}
                -dc={{ .Values.global.datacenter }}
          {{- if (and .Values.global.tls.caCert.secretName .Values.global.tls.caKey.secretName) }}
          volumeMounts:
            - name: consul-ca-cert
              mountPath: /consul/tls/ca/cert
              readOnly: true
            - name: consul-ca-key
              mountPath: /consul/tls/ca/key
              readOnly: true
          {{- end }}
          resources:
            requests:
              memory: {{ default "50Mi" .Values.global.tls.init.resources.requests.memory }}
              cpu: {{ default "50m" .Values.global.tls.init.resources.requests.cpu }}
            limits:
              memory: {{ default "50Mi" .Values.global.tls.init.resources.limits.memory }}
              cpu: {{ default "50m" .Values.global.tls.init.resources.limits.cpu }}
          securityContext:
            {{- include "consul.globalContainerSecurityContext" . | nindent 12 }}
{{- end }}
{{- end }}
