{{- if (or (and (ne (.Values.server.enabled | toString) "-") .Values.server.enabled) (and (eq (.Values.server.enabled | toString) "-") .Values.global.enabled)) }}
{{- if and .Values.global.tls.enabled .Values.global.tls.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "consul.fullname" . }}-tls-server-certificate
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
spec:
  secretName: {{ template "server.tlsSecretName" . }}
  duration: {{ default 730 .Values.global.tls.certManager.durationDays | mul 24 }}h0m0s
  commonName: consul-server
  isCA: false
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
{{ ( include "consul.certDnsNames" . | indent 4) }}
  ipAddresses:
{{ ( include "consul.certIpAddresses" . | indent 4) }}
  issuerRef:
    name: {{ template "consul.fullname" . }}-tls-server-issuer
    kind: Issuer
    group: cert-manager.io
{{- end }}
{{- end }}