{{- if (or (and (ne (.Values.server.enabled | toString) "-") .Values.server.enabled) (and (eq (.Values.server.enabled | toString) "-") .Values.global.enabled)) }}
{{- if and .Values.global.tls.enabled .Values.global.tls.certManager.enabled (not .Values.global.tls.certManager.clusterIssuerName) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "consul.fullname" . }}-tls-ca-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
{{- end }}