{{- if and .Values.global.tls.enabled ( and (not .Values.global.tls.certManager.enabled) (eq (include "client.certificatesSpecified" .) "true")) }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ template "consul.fullname" . }}-client-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.client.tls.certificates.crt | quote }}
  tls.key: {{ .Values.client.tls.certificates.key | quote }}
  ca.crt: {{ .Values.client.tls.certificates.ca | quote }}
{{- end }}