{{- if and .Values.global.tls.enabled ( and (not .Values.global.tls.certManager.enabled) (eq (include "server.certificatesSpecified" .) "true")) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "consul.caCertSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.server.tls.certificates.ca | quote }} # this is required for some components that uses tls.crt as CA cert.
  ca.crt: {{ .Values.server.tls.certificates.ca | quote }}
{{- end }}