{{- if and .Values.global.tls.enabled ( and (not .Values.global.tls.certManager.enabled) (eq (include "server.certificatesSpecified" .) "true")) }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ template "server.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.server.tls.certificates.crt | quote }}
  tls.key: {{ .Values.server.tls.certificates.key | quote }}
  ca.crt: {{ .Values.server.tls.certificates.ca | quote }}
{{- end }}