{{- if (or (and (ne (.Values.server.enabled | toString) "-") .Values.server.enabled) (and (eq (.Values.server.enabled | toString) "-") .Values.global.enabled)) }}
{{- if and .Values.global.tls.enabled .Values.global.tls.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "consul.fullname" . }}-tls-ca-certificate
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
spec:
  secretName: {{ template "consul.caCertSecretName" . }}
  duration: {{ default 730 .Values.global.tls.certManager.durationDays | mul 24 }}h0m0s
  commonName: consul-ca
  isCA: true
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
  {{- if .Values.global.tls.certManager.clusterIssuerName }}
    name: {{ .Values.global.tls.certManager.clusterIssuerName }}
    kind: ClusterIssuer
  {{- else }}
    name: {{ template "consul.fullname" . }}-tls-ca-issuer
    kind: Issuer
  {{- end }}
    group: cert-manager.io
{{- end }}
{{- end }}