build:
  env:
    type: application-integration
    version: openshift-dd-2
  networkRules: integration

  integration:
    multi_image_descriptor: true
    dmp_descriptor: true

publication:
  application-manifest:
    am-mf: application.mf
    am-zip: application.zip

deployment:
  mode: reinstall
  availability_check: true
  availability:
    resource: Deployment
    conditions: Successful
    interval: 30
    max_tries: 20
    delay: 60
cloud:
  type: helm
  url: https://ci-master.openshift.sdntest.netcracker.com:6443
  project: consul-service

integration:
  - type: find-latest-deployment-descriptor
    repo: PROD.Platform.Streaming/consul-service
    location: master
    docker-image-id: timestamp
    deploy-param: consulIntegrationTests
    service-name: consul-integration-tests