{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ .Values.serviceAccount.name }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - list
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - delete
      - patch
  {{- if .Values.integrationTests.statusWritingEnabled }}
  - apiGroups:
      - apps
    resources:
      - deployments/status
    verbs:
      - get
      - list
      - update
      - patch
  {{- end }}
  - apiGroups:
      - apps
    resources:
      - statefulsets/scale
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - list
{{- end }}
