version: '2.2'
services:
  consul:
    image: hashicorp/consul:1.22.7@sha256:a230dcea0bb107bd7958a912d1429fb7f9d399637de7ffb814b34412b9e8c543
    ports:
      - 8500:8500
  consul-backup-daemon:
    image: ghcr.io/netcracker/qubership-consul-backup-daemon:latest@sha256:299a2064eea18099b46eaf6c8ccc3240529fdbea574e4f2a2d4b8932d0f5317b
    ports:
      - 8080:8080
    links:
      - consul
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - BACKUP_SCHEDULE=0 * * * *
      - EVICTION_POLICY=1h/1h
      - CONSUL_BACKUP_DAEMON_DEBUG=DEBUG
      - LOG_LEVEL=DEBUG