{{- if eq (include "consul.enableDisasterRecovery" .) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "consul.fullname" . }}-disaster-recovery
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - watch
      - update
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/scale
      - statefulsets
    verbs:
      - get
      - list
      - update
{{- end }}