{{- if eq (include "consul.enableDisasterRecovery" .) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "consul.fullname" . }}-disaster-recovery
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
{{- end }}