{{- if and (eq (include "disaster-recovery.tlsEnabled" .) "true") .Values.global.tls.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "consul.fullname" . }}-drd-tls-certificate
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
spec:
  secretName: {{ template "disaster-recovery.certSecretName" . }}
  duration: {{ default 365 .Values.global.tls.certManager.durationDays | mul 24 }}h0m0s
  commonName: consul-drd-ca
  isCA: false
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
{{ include "disaster-recovery.certDnsNames" . | indent 4 }}
  ipAddresses:
{{ include "disaster-recovery.certIpAddresses" . | indent 4 }}
  issuerRef:
  {{- if .Values.global.tls.certManager.clusterIssuerName }}
    name: {{ .Values.global.tls.certManager.clusterIssuerName }}
    kind: ClusterIssuer
  {{- else }}
    name: {{ template "consul.fullname" . }}-tls-ca-issuer
    kind: Issuer
  {{- end }}
    group: cert-manager.io
{{- end }}