name: Run Consul Pipeline

on:
  push:
    branches:
      - improvement/run_tests

jobs:
  Get_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Branch Name
      run: echo ${{ github.ref }}
  Consul-Pipeline:
    uses: Netcracker/qubership-test-pipelines/.github/workflows/consul.yaml@main
    with:
      branch: main


