{
 "title": "Consul Monitoring",
 "description": "Consul Prometheus Monitoring",
 "tags": [
  "Prometheus",
  "Consul"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cloud", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(consul_autopilot_healthy, cluster)"
    }
   },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(consul_autopilot_healthy{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values(consul_autopilot_healthy{cluster=\"$cluster\"}, datacenter)"
    }
   },
   {
    "name": "fullname",
    "label": "Server name",
    "query": {
     "query": "label_values(kube_statefulset_replicas{cluster=\"$cluster\", namespace=\"$project\"}, statefulset)"
    }
   },
   { "name": "role", "label": "Role", "query": "Server, Client" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Consul Cluster Health",
   "type": "stat",
   "description": "The overall health of the local server cluster",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{exported_namespace=\"$project\",exported_pod=~\"$fullname-[0-9]+$\",condition=\"false\", cluster=\"$cluster\"}) / sum(kube_pod_status_ready{exported_namespace=\"$project\",exported_pod=~\"$fullname-[0-9]+$\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Leader Last Contact",
   "type": "timeseries",
   "description": "The time (in milliseconds) since the leader was last able to contact the follower nodes when checking its leader lease",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "last contact time",
     "expr": "max(consul_raft_leader_lastContact{namespace=\"$project\",datacenter=\"$datacenter\",role=\"Server\", cluster=\"$cluster\", quantile=\"0.9\"})",
     "legendFormat": "Last contact time",
     "measurement": "consul_raft_leader_lastContact",
     "query": "SELECT max(\"90_percentile\") FROM \"consul_raft_leader_lastContact\" WHERE (\"project_name\" =~ /^$project$/ AND \"datacenter\" =~ /^$datacenter$/ AND \"role\" = 'Server') AND $timeFilter GROUP BY time($inter) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consul Servers",
   "type": "table",
   "description": "Information about which server is the leader",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "max(consul_server_isLeader{namespace=\"$project\",datacenter=\"$datacenter\",role=\"Server\", cluster=\"$cluster\"}) by (pod)",
     "measurement": "consul_cluster_servers",
     "query": "SELECT last(\"is_leader\") AS \"Leader\" FROM \"consul_cluster_servers\" WHERE (\"project_name\" =~ /^$project$/ AND \"datacenter\" =~ /^$datacenter$/ AND \"role\" = 'Server') AND $timeFilter GROUP BY \"server_name\""
    },
    {
     "expr": "max(consul_autopilot_healthy{namespace=\"$project\",datacenter=\"$datacenter\",role=\"Server\", cluster=\"$cluster\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Servers Count",
   "type": "timeseries",
   "description": "The actual and expected number of servers in the Consul cluster",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "servers count",
     "expr": "sum(kube_pod_status_ready{exported_namespace=\"$project\",exported_pod=~\"$fullname-[0-9]+$\", cluster=\"$cluster\"})",
     "legendFormat": "Actual servers count",
     "measurement": "consul_cluster_health",
     "query": "SELECT \"servers_count\" FROM \"consul_cluster_health\" WHERE (\"project_name\" =~ /^$project$/ AND \"datacenter\" =~ /^$datacenter$/ AND \"role\" = 'Server') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "expected count",
     "expr": "sum(kube_statefulset_replicas{exported_namespace=\"$project\",statefulset=~\"$fullname\", cluster=\"$cluster\"})",
     "legendFormat": "Expected servers count",
     "measurement": "consul_cluster_health",
     "query": "SELECT \"expected_count\" FROM \"consul_cluster_health\" WHERE (\"project_name\" =~ /^$project$/ AND \"datacenter\" =~ /^$datacenter$/ AND \"role\" = 'Server') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Leadership Changes",
   "type": "table",
   "description": "The counters which are incremented when a Consul server starts an election process.\n\nConsul cluster should have a stable leader. If there are frequent elections or leadership changes, it would likely indicate network issues between the Consul servers, or that the Consul servers themselves are unable to keep up with the load",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "max(consul_raft_state_candidate{namespace=\"$project\",datacenter=\"$datacenter\",role=\"Server\", cluster=\"$cluster\"}) by (pod)",
     "measurement": "consul_raft_state_candidate",
     "query": "SELECT last(\"value\") FROM \"consul_raft_state_candidate\" WHERE (\"project_name\" =~ /^$project$/ AND \"datacenter\" =~ /^$datacenter$/ AND \"role\" = 'Server') AND $timeFilter GROUP BY \"host\""
    }
   ]
  },
  {
   "title": "KV Store Timing",
   "type": "timeseries",
   "description": "The time (in milliseconds) required to complete an update to the KV store",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "avg(consul_kvs_apply{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\", quantile=\"0.9\"}) by (pod)",
     "legendFormat": "{{pod}}",
     "measurement": "consul_kvs_apply",
     "query": "SELECT mean(\"90_percentile\") FROM \"consul_kvs_apply\" WHERE (\"project_name\" =~ /^$project$/ AND \"datacenter\" =~ /^$datacenter$/ AND \"role\" = 'Server') AND $timeFilter GROUP BY time($inter), \"host\" fill(linear)",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Raft Transactions",
   "type": "timeseries",
   "description": "The number of Raft transactions occurring over the interval",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "rate(consul_raft_apply{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{pod}}",
     "measurement": "consul_raft_apply",
     "query": "SELECT mean(\"value\") FROM \"consul_raft_apply\" WHERE (\"project_name\" =~ /^$project$/ AND \"datacenter\" =~ /^$datacenter$/ AND \"role\" = 'Server') AND $timeFilter GROUP BY time($inter), \"host\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Raft Log Commit Time",
   "type": "timeseries",
   "description": "The time (in milliseconds) required to commit a new entry to the Raft log on the leader",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "avg(consul_raft_commitTime{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\", quantile=\"0.9\"}) by (pod)",
     "legendFormat": "{{host}}",
     "measurement": "consul_raft_commitTime",
     "query": "SELECT mean(\"90_percentile\") FROM \"consul_raft_commitTime\" WHERE (\"project_name\" =~ /^$project$/ AND \"datacenter\" =~ /^$datacenter$/ AND \"role\" = 'Server') AND $timeFilter GROUP BY time($inter), \"host\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Server Container CPU Usage",
     "type": "timeseries",
     "description": "The CPU usage by server containers. Limits show the maximum number of CPUs the container can use",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$tag_host",
       "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"$project\",pod=~\"$fullname-[0-9]+\",container=\"consul\", cluster=\"$cluster\"}[2m])) by (pod)) * 1000",
       "legendFormat": "{{pod}}:usage",
       "measurement": "cpu",
       "query": "SELECT mean(\"usage_user\") FROM \"cpu\" WHERE (\"project_name\" =~ /^$project$/ AND \"cpu\" = 'cpu-total' AND \"datacenter\" =~ /^$datacenter$/ AND \"role\" = 'Server') AND $timeFilter GROUP BY time($inter), \"host\" fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "usage rate: $tag_pod_name",
       "expr": "(avg(kube_pod_container_resource_limits{exported_namespace=\"$project\",exported_pod=~\"$fullname-[0-9]+\",container=\"consul\",resource=\"cpu\", cluster=\"$cluster\"}) by (exported_pod)) * 1000",
       "legendFormat": "{{exported_pod}}:limit",
       "query": "SELECT mean(value) FROM \"cpu/usage_rate\" WHERE \"type\" = 'pod_container' AND \"namespace_name\" = '$namespace' AND \"pod_name\" =~  /kafka-[\\d]-[\\d]/ AND \"pod_name\" =~ /^$side/ AND $timeFilter GROUP BY time($__interval), pod_name fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Server Container Memory Usage",
     "type": "timeseries",
     "description": "The memory usage by server container. Limits show the maximum amount of memory the container can use",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "$tag_host",
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$project\",pod=~\"$fullname-[0-9]+\",container=\"consul\", cluster=\"$cluster\"}) by (pod)",
       "legendFormat": "{{pod}}:usage",
       "measurement": "mem",
       "query": "SELECT mean(\"used_percent\") FROM \"mem\" WHERE (\"project_name\" =~ /^$project$/ AND \"datacenter\" =~ /^$datacenter$/ AND \"role\" = 'Server') AND $timeFilter GROUP BY time($inter), \"host\" fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "limit: $tag_pod_name",
       "expr": "sum(kube_pod_container_resource_limits{exported_namespace=\"$project\",exported_pod=~\"$fullname-[0-9]+\",container=\"consul\",resource=\"memory\", cluster=\"$cluster\"}) by (exported_pod)",
       "legendFormat": "{{exported_pod}}:limit",
       "query": "SELECT mean(value) FROM \"memory/limit\" WHERE \"type\" = 'pod_container' AND \"namespace_name\" = '$namespace' AND \"pod_name\" =~ /kafka-[\\d]-[\\d]/ AND \"pod_name\" =~ /^$side/ AND $timeFilter GROUP BY time($__interval), pod_name fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$project\",pod=~\"$fullname-[0-9]+\",container=\"consul\", cluster=\"$cluster\"}) by (pod)",
       "legendFormat": "{{pod}}:allocated"
      }
     ]
    },
    {
     "title": "Consul Process Memory Usage",
     "type": "timeseries",
     "description": "The number of bytes allocated by the Consul process",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "$tag_host",
       "expr": "avg(consul_runtime_alloc_bytes{namespace=\"$project\",pod=~\"$fullname-[0-9]+\",role=\"Server\", cluster=\"$cluster\"}) by (pod)",
       "legendFormat": "{{host}}",
       "measurement": "consul_runtime_alloc_bytes",
       "query": "SELECT mean(\"value\") FROM \"consul_runtime_alloc_bytes\" WHERE (\"project_name\" =~ /^$project$/ AND \"datacenter\" =~ /^$datacenter$/ AND \"role\" = 'Server') AND $timeFilter GROUP BY time($inter), \"host\" fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "GC Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "GC Pause",
     "type": "timeseries",
     "description": "The number of nanoseconds consumed by stop-the-world garbage collection (GC) pauses since Consul started",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "alias": "$tag_host",
       "expr": "max(idelta(consul_runtime_total_gc_pause_ns{namespace=\"$project\",datacenter=\"$datacenter\",role=\"Server\", cluster=\"$cluster\"}[5m])) by (pod) >= 0",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "legendFormat": "{{pod}}",
       "measurement": "consul_runtime_total_gc_pause_ns",
       "query": "SELECT non_negative_difference(mean(\"value\")) FROM \"consul_runtime_total_gc_pause_ns\" WHERE (\"project_name\" =~ /^$project$/ AND \"datacenter\" =~ /^$datacenter$/ AND \"role\" = 'Server') AND $timeFilter GROUP BY time($inter), \"host\" fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GC Runs Rate",
     "type": "timeseries",
     "description": "The number of stop-the-world garbage collection (GC) runs  since Consul started",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host",
       "expr": "rate(consul_runtime_total_gc_runs{namespace=\"$project\",datacenter=\"$datacenter\",role=\"Server\", cluster=\"$cluster\"}[5m])",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "legendFormat": "{{pod}}",
       "measurement": "consul_runtime_total_gc_pause_ns",
       "query": "SELECT non_negative_difference(mean(\"value\")) FROM \"consul_runtime_total_gc_pause_ns\" WHERE (\"project_name\" =~ /^$project$/ AND \"datacenter\" =~ /^$datacenter$/ AND \"role\" = 'Server') AND $timeFilter GROUP BY time($inter), \"host\" fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Runtime Heap Objects",
     "type": "timeseries",
     "description": "Consul runtime heap objects count.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consul_runtime_heap_objects{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk Volume ",
     "type": "timeseries",
     "description": "Disk Volume stats",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "$tag_host",
       "expr": "kubelet_volume_stats_available_bytes{namespace=\"$project\", cluster=\"$cluster\"}",
       "legendFormat": "{{persistentvolumeclaim}}:available",
       "measurement": "diskio",
       "query": "SELECT non_negative_difference(mean(\"read_time\")) FROM \"diskio\" WHERE (\"project_name\" =~ /^$project$/ AND \"datacenter\" =~ /^$datacenter$/ AND \"role\" = 'Server') AND $timeFilter GROUP BY time($inter), \"host\" fill(linear)",
       "select": [
        [
         { "params": [ "read_time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host",
       "expr": "kubelet_volume_stats_used_bytes{namespace=\"$project\", cluster=\"$cluster\"}",
       "legendFormat": "{{persistentvolumeclaim}}:used",
       "measurement": "diskio",
       "query": "SELECT non_negative_difference(mean(\"read_time\")) FROM \"diskio\" WHERE (\"project_name\" =~ /^$project$/ AND \"datacenter\" =~ /^$datacenter$/ AND \"role\" = 'Server') AND $timeFilter GROUP BY time($inter), \"host\" fill(linear)",
       "select": [
        [
         { "params": [ "read_time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Raft Commit Rate",
     "type": "timeseries",
     "description": "Rate new entries to the Raft log on the leader.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(consul_raft_commitTime_count{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Raft Commit Time",
     "type": "timeseries",
     "description": "Measures the time it takes to commit a new entry to the Raft log on the leader.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(consul_raft_commitTime_sum{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Container FS Reads Rate",
     "type": "timeseries",
     "description": "Container fs reads rate.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_total{namespace=\"$project\", cluster=\"$cluster\",pod=~\"$fullname-[0-9]+$\", container=\"consul\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}:/dev/vda"
      }
     ]
    },
    {
     "title": "Container FS Writes Rate",
     "type": "timeseries",
     "description": "Container fs writes rate.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_total{namespace=\"$project\", cluster=\"$cluster\",pod=~\"$fullname-[0-9]+$\", container=\"consul\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Container FS Reads Bytes Rate",
     "type": "timeseries",
     "description": "Container fs reads bytes rate.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"$project\", cluster=\"$cluster\",pod=~\"$fullname-[0-9]+$\", container=\"consul\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Container FS Writes Bytes Rate",
     "type": "timeseries",
     "description": "Container fs writes bytes rate.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"$project\", cluster=\"$cluster\",pod=~\"$fullname-[0-9]+$\", container=\"consul\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "KV",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "KV Applies Rate",
     "type": "timeseries",
     "description": "Shows the rate of KV operations in interval buckets. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(consul_kvs_apply_count{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "KV Apply Time",
     "type": "timeseries",
     "description": "This measures the time it takes to complete an update to the KV store.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(consul_kvs_apply_sum{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transaction Apply Time",
     "type": "timeseries",
     "description": "Measures the time spent applying transaction operations.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "consul_txn_apply{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\", quantile=\"0.9\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "KV entries",
     "type": "timeseries",
     "description": "KV entries.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(consul_consul_state_kv_entries{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"})",
       "legendFormat": "KV"
      }
     ]
    }
   ]
  },
  {
   "title": "ACL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "ACL Login Rate",
     "type": "timeseries",
     "description": "Counts the number of times we login with ACL token by 5m. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(consul_acl_login_count{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ACL Logout Rate",
     "type": "timeseries",
     "description": "Counts the number of times we logout with ACL token by 5m. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(consul_acl_logout_count{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ACL Token Resolves Rate",
     "type": "timeseries",
     "description": "Counts the number of times we've resolves an ACL token by 5m. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(consul_acl_ResolveToken_count{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ACL Token Resolves",
     "type": "timeseries",
     "description": "Counts the number of times we've resolves an ACL token.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consul_acl_ResolveToken_count{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ACL Token Upserts Rate",
     "type": "timeseries",
     "description": "Counts the number of times we've upserts an ACL  token by 5m. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(consul_acl_token_upsert_count{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ACL Token Upserts ",
     "type": "timeseries",
     "description": "Counts the number of times we've upserts an ACL token.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consul_acl_token_upsert_count{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ACL Authmethod Upsets Rate",
     "type": "timeseries",
     "description": "Counts the number of times we've upsets an ACL authmethod by 5m. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(consul_acl_authmethod_upsert_count{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ACL Authmethod Upsets ",
     "type": "timeseries",
     "description": "Counts the number of times we've upsets an ACL authmethod.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consul_acl_authmethod_upsert_count{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ACL Bindingrule Upsets Rate",
     "type": "timeseries",
     "description": "Counts the number of times we've upsets an ACL bindingrule by 5m. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(consul_acl_bindingrule_upsert_count{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ACL Bindingrule Upsets ",
     "type": "timeseries",
     "description": "Counts the number of times we've upsets an ACL bindingrule.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consul_acl_bindingrule_upsert_count{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ACL Role Upsets Rate",
     "type": "timeseries",
     "description": "Counts the number of times we've upsets an ACL role by 5m. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(consul_acl_role_upsert_count{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ACL Role Upsets ",
     "type": "timeseries",
     "description": "Counts the number of times we've upsets an ACL role.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consul_acl_role_upsert_count{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ACL Policy Upsets Rate",
     "type": "timeseries",
     "description": "Counts the number of times we've upsets an ACL policy by 5m. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(consul_acl_policy_upsert_count{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ACL Policy Upsets ",
     "type": "timeseries",
     "description": "Counts the number of times we've upsets an ACL policy.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consul_acl_policy_upsert_count{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consul API HTTP Rate By Pod",
     "type": "timeseries",
     "description": "Consul API HTTP rate by pod. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(consul_api_http_count{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Consul API HTTP Rate By Path",
     "type": "timeseries",
     "description": "Consul API HTTP rate by path. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(consul_api_http_count{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}[5m])) by (path)",
       "legendFormat": "{{path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Catalog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Catalog Operations Rate",
     "type": "timeseries",
     "description": "This shows the rate of increase for catalog register and deregister operations. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(consul_catalog_register_count{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{pod}}:register"
      },
      {
       "expr": "rate(consul_catalog_deregister_count{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{pod}}:deregister"
      }
     ]
    },
    {
     "title": "Catalog Operation Time",
     "type": "timeseries",
     "description": "Measures the time it takes to complete catalog register or deregister operations.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "consul_catalog_register{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\", quantile=\"0.9\"}",
       "legendFormat": "{{pod}}:register"
      },
      {
       "expr": "consul_catalog_deregister{namespace=\"$project\",datacenter=\"$datacenter\",role=~\"$role\", cluster=\"$cluster\", quantile=\"0.9\"}",
       "legendFormat": "{{pod}}:deregister"
      }
     ]
    }
   ]
  }
 ]
}