{{- if (eq (include "remove-tokens.enabled" .) "true") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "consul.fullname" . }}-remove-tokens-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
{{- range . }}
  - name: {{ .name }}
{{- end }}
{{- end }}
{{- end }}
